version: "2"
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dupword
    - durationcheck
    - funlen
    - gosec
    - iface
    - misspell
    - nestif
    - nolintlint
    - revive
    - tagalign
    - unconvert
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
