name: Pull Request

on:
  pull_request_target:

jobs:
  StaticAnalysis:
    uses: EncoreDigitalGroup/ci-workflows/.github/workflows/go_staticAnalysis.yml@v2
    with:
      branch: "${{ github.head_ref }}"
      goVersion: "1.24.1"