name: Pull Request

on:
    pull_request:

concurrency:
    group: ${{ github.repository }}-${{ github.event.pull_request.number }}-pullRequest
    cancel-in-progress: true

jobs:
    Setup:
        runs-on: ubuntu-latest
        outputs:
            go-version: ${{ steps.config.outputs.go-version }}
        steps:
            -   name: Set configuration
                id: config
                run: echo "go-version=1.24.1" >> $GITHUB_OUTPUT

    StaticAnalysis:
        needs: Setup
        uses: EncoreDigitalGroup/ci-workflows/.github/workflows/go_staticAnalysis.yml@v2
        with:
            branch: "${{ github.head_ref }}"
            goVersion: ${{ needs.Setup.outputs.go-version }}

    Tests:
        needs: Setup
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout code
                uses: actions/checkout@v4
                with:
                    ref: ${{ github.head_ref }}

            -   name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version: ${{ needs.Setup.outputs.go-version }}

            -   name: Run tests (stable)
                run: go test -v ./...

            -   name: Run tests (experimental)
                run: go test -tags experimental -v ./...